### ISSUE TITLE
FatalThrowableError

### ISSUE THREAD

**Issue by ghost** [Klaasie/oc-pushbullet-plugin#1]
**FatalThrowableError**
`Type error: Argument 1 passed to Klaasie\Pushbullet\Classes\EventListeners\LogListener::subscribe() must be an instance of Illuminate\Events\Dispatcher, instance of October\Rain\Events\Dispatcher given, called in /home/admin/web/xxxxxxxx.com/public_html/vendor/october/rain/src/Events/Dispatcher.php on line 135`

When I'm trying to access to settings page on backend

OCTOBER BUILD: 419

**Comment by Klaasie** [comment]
This issue should be fixed in version 1.0.3
